// <auto-generated />
using System;
using KARDEM.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KARDEM.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20250617055758_harcbilgi2")]
    partial class harcbilgi2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KARDEM.Models.Dosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DosyaNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("EsasNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KararNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("KararTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KararTebligTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MahkemeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EkleyenKullaniciId");

                    b.HasIndex("MahkemeId");

                    b.ToTable("Dosyalar");
                });

            modelBuilder.Entity("KARDEM.Models.Harc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DosyaId")
                        .HasColumnType("int");

                    b.Property<int?>("DosyaId1")
                        .HasColumnType("int");

                    b.Property<decimal>("HarcMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HarcTuru")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarcYazilacakTarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("HarcinTarafi")
                        .HasColumnType("int");

                    b.Property<bool>("YazilmaDurumu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DosyaId");

                    b.HasIndex("DosyaId1")
                        .IsUnique()
                        .HasFilter("[DosyaId1] IS NOT NULL");

                    b.ToTable("HarcBilgileri");
                });

            modelBuilder.Entity("KARDEM.Models.IstinafBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DilekceTebligTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DosyaGonderildiMi")
                        .HasColumnType("bit");

                    b.Property<int>("DosyaId")
                        .HasColumnType("int");

                    b.Property<string>("IstinafEdenTaraf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IstinafTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SureKontroluYapildiMi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DosyaId");

                    b.ToTable("IstinafBilgileri");
                });

            modelBuilder.Entity("KARDEM.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KARDEM.Models.Mahkeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IstinafSuresiGun")
                        .HasColumnType("int");

                    b.Property<int>("KesinlesmeSuresiGun")
                        .HasColumnType("int");

                    b.Property<int>("TemyizSuresiGun")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mahkemeler");
                });

            modelBuilder.Entity("KARDEM.Models.MahkemeYetki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("MahkemeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("MahkemeId");

                    b.ToTable("MahkemeYetkileri");
                });

            modelBuilder.Entity("KARDEM.Models.Dosya", b =>
                {
                    b.HasOne("KARDEM.Models.Kullanici", "EkleyenKullanici")
                        .WithMany()
                        .HasForeignKey("EkleyenKullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("KARDEM.Models.Mahkeme", "Mahkeme")
                        .WithMany("Dosyalar")
                        .HasForeignKey("MahkemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkleyenKullanici");

                    b.Navigation("Mahkeme");
                });

            modelBuilder.Entity("KARDEM.Models.Harc", b =>
                {
                    b.HasOne("KARDEM.Models.Dosya", "Dosya")
                        .WithMany()
                        .HasForeignKey("DosyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KARDEM.Models.Dosya", null)
                        .WithOne("HarcBilgileri")
                        .HasForeignKey("KARDEM.Models.Harc", "DosyaId1");

                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("KARDEM.Models.IstinafBilgisi", b =>
                {
                    b.HasOne("KARDEM.Models.Dosya", "Dosya")
                        .WithMany("IstinafBilgileri")
                        .HasForeignKey("DosyaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dosya");
                });

            modelBuilder.Entity("KARDEM.Models.MahkemeYetki", b =>
                {
                    b.HasOne("KARDEM.Models.Kullanici", "Kullanici")
                        .WithMany("MahkemeYetkileri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KARDEM.Models.Mahkeme", "Mahkeme")
                        .WithMany("YetkiliKullanicilar")
                        .HasForeignKey("MahkemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Mahkeme");
                });

            modelBuilder.Entity("KARDEM.Models.Dosya", b =>
                {
                    b.Navigation("HarcBilgileri")
                        .IsRequired();

                    b.Navigation("IstinafBilgileri");
                });

            modelBuilder.Entity("KARDEM.Models.Kullanici", b =>
                {
                    b.Navigation("MahkemeYetkileri");
                });

            modelBuilder.Entity("KARDEM.Models.Mahkeme", b =>
                {
                    b.Navigation("Dosyalar");

                    b.Navigation("YetkiliKullanicilar");
                });
#pragma warning restore 612, 618
        }
    }
}
